[features]
seeds = false
skip-lint = false
[programs.localnet]
demo_pda = "9spvMuHiirYzi8VMBp1AXYVcJyWk26DU3BhjoSa7KKEr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/darius/solana-wallets/test-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
